openapi: 3.0.3
info:
  title: SejutaCita API -
  version: 1.0.0

servers:
- url: http://167.99.29.250/
  description: Development

tags:
- name: SC-USER
  description: 'SC USER API'
- name: SC-AUTH
  description: 'SC AUTH API'

paths:

### FOR SC-AUTH
  /sc-auth/login:
    post:
      operationId: Login
      summary: Login
      description: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      tags: 
        - SC-AUTH
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data:
                    type: object
                    example:
                      $ref: '#/components/examples/login/value'
  /sc-auth/refresh:
    post:
      operationId: Refresh token
      summary: Refresh token
      description: Refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Refresh'

      tags: 
        - SC-AUTH
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data:
                    type: object
                    example:
                      $ref: '#/components/examples/login/value'


  /sc-user/users:
    get:
      operationId: Get All Users
      summary: Get All Users
      description: Get All Users
      security:
        - bearerAuth: []
      tags: 
        - SC-USER
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data:
                    type: array
                    example:
                      - $ref: '#/components/examples/user/value'
                      - $ref: '#/components/examples/user/value'

    post:
      operationId: Create User
      summary: Create User
      description: Create User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      security:
        - bearerAuth: []
      tags: 
        - SC-USER
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data:
                    type: object
                    example:
                      $ref: '#/components/examples/user/value'
  /sc-users/user/{userId}: 
    delete:
      operationId: Delete User by User Id
      summary: Delete User by User Id
      description: Delete User by User Id
      parameters: 
        - $ref: '#/components/parameters/userId'
      security:
        - bearerAuth: []      
      tags: 
        - SC-User
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Success"
                  message:
                    type: string
                    example: "User deleted successfully!"

    put: 
      operationId: Update User by User Id
      summary: Update User by User Id
      description: Update User by User Id
      security:
        - bearerAuth: []
      requestBody:
        # required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      tags: 
        - SC-USER
      parameters: 
        - $ref: '#/components/parameters/userId'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string  
                    example: 'Success'
                  data:
                    type: object
                    example:
                      $ref: '#/components/examples/user/value'
  
    get:
      operationId: Get User by User Id
      summary: Get User by User Id
      description: Get User by User Id
      security:
        - bearerAuth: []      
      tags: 
        - SC-USER
      parameters: 
        - $ref: '#/components/parameters/userId'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Success"
                  data:
                    type: object
                    example:
                      $ref: '#/components/examples/user/value'

components:
  examples:
    user:
      value:
        _id: "60265cf04f823a40f6622497"
        username: "aaaddd"
        password: "asdasd"
        address: "qqqq"
        role: "admin"
        createdAt: "2021-02-12T10:48:16.253Z"
        updatedAt: "2021-02-12T10:48:16.253Z"      
    login:
      value: 
        accessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwMjY1Y2YwNGY4MjNhNDBmNjYyMjQ5NyIsInVzZXJuYW1lIjoiYWFhZGRkIiwicGFzc3dvcmQiOiIkMmEkMDgkWUtnSWxBQ0pyRlNKSHJQSjBmcTUwLlpEYjg4NE9ET2tWZXJHVEQ2S0lCbDMxQXM1a3NiVWUiLCJhZGRyZXNzIjoicXFxcSIsInJvbGUiOiJhZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMTJUMTA6NDg6MTYuMjUzWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMTJUMTA6NDg6MTYuMjUzWiIsIl9fdiI6MH0sImlhdCI6MTYxMzIxNTU3NCwiZXhwIjoxNjEzMjE2MTc0fQ._pWd9dafWYzt-MNtSK5YCKxtx0zwGrUBivJpLppEa4M"
        refreshToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYwMjY1Y2YwNGY4MjNhNDBmNjYyMjQ5NyIsInVzZXJuYW1lIjoiYWFhZGRkIiwicGFzc3dvcmQiOiIkMmEkMDgkWUtnSWxBQ0pyRlNKSHJQSjBmcTUwLlpEYjg4NE9ET2tWZXJHVEQ2S0lCbDMxQXM1a3NiVWUiLCJhZGRyZXNzIjoicXFxcSIsInJvbGUiOiJhZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMTJUMTA6NDg6MTYuMjUzWiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMTJUMTA6NDg6MTYuMjUzWiIsIl9fdiI6MH0sImlhdCI6MTYxMzIxNTU3NH0.rxMzz8jjLFwkVqEYiCwJ70gkJMwPruJHfTcAY6OAlbU"
        user: {
            _id: "60265cf04f823a40f6622497",
            username: "aaaddd",
            password: "asdasd",
            address: "qqqq",
            role: "admin",
            createdAt: "2021-02-12T10:48:16.253Z",
            updatedAt: "2021-02-12T10:48:16.253Z"
        }
  parameters:
    userId:
      name: userId
      in: path
      description: User ID
      required: true
      schema:
        type: string
 
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        address:
          type: string
        role:
          type: string
    Refresh:
      type: object
      properties:
        token:
          type: string
    Login:
      type: object
      properties:
        username:
          type: string
          description: Username
        password: 
          type: string
          description: Password

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
 